import type { Metadata } from 'next'
import './globals.css'
import { Navigation } from '@/app/navigation'
import { mainFont } from './fonts'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${mainFont.className} mx-auto max-w-[75%] py-8`}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
