import type { Metadata } from 'next'
import './globals.css'
import { Navigation } from '@/components/navigation'
import { lusitana } from './fonts'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lusitana.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
